### ISSUE TITLE
Discard-to-demote transformation flags do not change cache hash

### ISSUE THREAD

**Issue by kuhar** [GPUOpen-Drivers/llpc#1666]
Enabling discard-to-demote transforms affected generated code. Currently, they also influence the hashes printed in `// LLPC calculated hash results`, but not in the cache hash embedded in the Elf note (`.xgl_cache_info: { .128_bit_cache_hash:`).

You can verify the current behavior by checking out the new test from thi PR: https://github.com/GPUOpen-Drivers/llpc/pull/1665.

The task is to check if discard-to-demote should affect both flags or none, and make an appropriate fix.

**Comment by kuhar** [comment]
Based on discussion with Steven. Currently:
-  The only options that are included in cache hash are those set by pipeline state.
-  All the other options are considered 'global' and included in the [compiler options hash](https://github.com/GPUOpen-Drivers/llpc/blob/7c02878905ce7e0cf6a3dece5965c4102fcc10fe/llpc/context/llpcCompiler.cpp#L412) but not in [PC UUID](https://github.com/GPUOpen-Drivers/xgl/blob/89a4cf115b9a2972ff00e2fe4959f4f1c8e7175b/icd/api/vk_physical_device.cpp#L612).
-  Discard-to-demote options are not representable in pipeline state and thus don't impact cache hash calculation.

**Comment by s-perron** [comment]
That seems to be right.  Including the options in the compiler options hash means that LLPC will not load an incorrect internal shader cache.

However, I still wonder what is stopping the application provided cache from being generated with one set of options and then used with a different set of options.  This could cause unexpected error.  As it stands, I don't think this is a big deal because it would seem to be very hard to do.  However, it is worth understanding because of options like discard-to-demote, which are needed for correctness.
