### ISSUE TITLE
LLPC does not employ information hiding

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#1750]
One of the biggest problems I currently have with LLPC is that all of the main data structures are structs (as opposed to classes) with all members public and no member functions.  This makes code more difficult to refactor. It also makes the code too concerned with smaller details making the code harder to read.  It also places references to the member in many different files making it harder to find all of the places to add code when a new member is being added.  Hashing is an example of this.

I am proposing that we change define classes that correspond to the structs in [vkgcDefs.h](https://github.com/GPUOpen-Drivers/llpc/blob/64aac8be4e3eb205f9808b280a70c9427b71572f/include/vkgcDefs.h) and [llpc.h](https://github.com/GPUOpen-Drivers/llpc/blob/64aac8be4e3eb205f9808b280a70c9427b71572f/llpc/include/llpc.h).

1. These classes will be internal to llpc & lgc.
2. They will each have their own header file and implementation file.
3. A reasonable effort will be made to move code to be member function of the classes.  Hashing and initialization are good examples of function that exists far from the struct that would be best in the class.
4. There will be code to convert between the structs and the classes, so we can stage the changes. This also means XGL will not have to change, because the public interface will not.

After all of the changes are done, we could consider making the classes part of the public interface, changing XGL, and removing the structs.

I am unsure if this will actually make the code better, but I strong believe it will.  This will be a longer process, and I want to make sure everybody in on board before I start making the changes.

**Comment by trenouf** [comment]
[AMD Official Use Only]

Hi Steven

Just a placeholder reply for now...

We need to discuss this internally. A complicating factor I can think of immediately is that these are structs in the LLPC interface, and that interface (and the hashing and logging code) is shared with the driver path that uses the proprietary compiler.

Thanks.

-tpr

From: Steven Perron ***@***.***>
Date: Monday, 28 March 2022 at 17:34
To: GPUOpen-Drivers/llpc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GPUOpen-Drivers/llpc] LLPC does not employ information hiding (Issue #1750)

One of the biggest problems I currently have with LLPC is that all of the main data structures are structs (as opposed to classes) with all members public and no member functions. This makes code more difficult to refactor. It also makes the code too concerned with smaller details making the code harder to read. It also places references to the member in many different files making it harder to find all of the places to add code when a new member is being added. Hashing is an example of this.

I am proposing that we change define classes that correspond to the structs in vkgcDefs.h<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGPUOpen-Drivers%2Fllpc%2Fblob%2F64aac8be4e3eb205f9808b280a70c9427b71572f%2Finclude%2FvkgcDefs.h&data=04%7C01%7Ctim.renouf%40amd.com%7Cf457be8286a5493b496008da10d8d8df%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637840820781485621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EBd2C98f0q7aVbHOD116%2BLS%2FNjgXJaVwdeEhxy460X0%3D&reserved=0> and llpc.h<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGPUOpen-Drivers%2Fllpc%2Fblob%2F64aac8be4e3eb205f9808b280a70c9427b71572f%2Fllpc%2Finclude%2Fllpc.h&data=04%7C01%7Ctim.renouf%40amd.com%7Cf457be8286a5493b496008da10d8d8df%7C3dd8961fe4884e608e11a82d994e183d%7C0%7C0%7C637840820781485621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GWHLoTU5tW2eb%2B23Jd02lZeFCeMtHY6j3nnOVUGYy30%3D&reserved=0>.

  1.  These classes will be internal to llpc & lgc.
  2.  They will each have their own header file and implementation file.
  3.  A reasonable effort will be made to move code to be member function of the classes. Hashing and initialization are good examples of function that exists far from the struct that would be best in the class.
  4.  There will be code to convert between the structs and the classes, so we can stage the changes. This also means XGL will not have to change, because the public interface will not.

After all of the changes are done, we could consider making the classes part of the public interface, changing XGL, and removing the structs.

I am unsure if this will actually make the code better, but I strong believe it will. This will be a longer process, and I want to make sure everybody in on board before I start making the changes.

**Comment by nhaehnle** [comment]
> It also places references to the member in many different files making it harder to find all of the places to add code when a new member is being added. Hashing is an example of this.

Are there examples other than hashing, and why would this be improved by information hiding? Information hiding just replaces the problem of searching for member *variable* uses with the problem of searching for member *function* uses.

It seems to me that perhaps the core issue is not so much information hiding but that certain "generic functionality" is spread across various places instead of being centralized in a single source file?

**Comment by nhaehnle** [comment]
I think the resolution of this is that the structures in vkgcDefs.h and llpc.h will stay as-is.

There is a general desire to reduce the amount of magic out-of-IR state which will help address the underlying problem over time as far as internal use of these structures is concerned, but there's no reason to change the interfaces with the driver.
