### ISSUE TITLE
Make XFB query counter increment even if XFB output are not written to

### ISSUE THREAD

**Issue by xuechen417** [GPUOpen-Drivers/llpc#2109]
**Description**
`VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT` is expected to work if the shader doesn't write to any of its Xfb decorated outputs. The [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#queries-transform-feedback) said "For each drawing command, the count is incremented as vertex attribute outputs are captured to the transform feedback buffers while transform feedback is active." And the author has confirmed that "if the shader doesn't write to the variable, then what's captured in the Xfb buffer is uninitialized data, but data is still captured. In that case, both counters would increment".

Currently, we don't work well for this case. The related cts tests are
_dEQP-VK.transform_feedback.simple.multiquery_omit_write_*
_dEQP-VK.transform_feedback.simple.query_omit_write_0_*__

Pipeline dump for _dEQP-VK.transform_feedback.simple.query_omit_write_0_4_32bits_is here: [issue.zip](https://github.com/GPUOpen-Drivers/llpc/files/9925439/issue.zip)

A glance at the geometry shader
```
#version 450

layout(points) in;
layout(location = 0) in vec4 in0[];

layout(points, max_vertices = 1) out;
layout(xfb_buffer = 0, xfb_offset = 0, xfb_stride = 16, location = 0) out vec4 out0;

void main(void)
{
    EmitVertex();
    EndPrimitive();
}
```
Current query result
Primitives Written   : 0
Primitives Needed  : 0
Expected query result
Primitives Written   : 4 
Primitives Needed  : 4

Root cause:
The primitive written count is from the execution of tbuffer_store for XFB. The counter is zero because tbuffer_store is missing due to no data written to XFB buffer.

**Solution**
How to increment the primitve written counter even if XFB captured data is uninitialized?
Try to utilize a dummy tbuffer_store as a workaround.
There are two questions to be discussed:
1. We should put the workaround in the front-end or middle-end?
2. Can we reuse `lgc::ResourceUsage::enableXfb` or a new flag to tell us to just create a dummy tbuffer store without exp instrustion?

**Comment by xuechen417** [comment]
> As a matter of general principle, issues like this should not be arguing from CTS tests. The question is: what does the spec mandate?

Got it. I have updated the issue. Is it OK?
> 
> Without consulting the spec explicitly, the increment of the counters should be happening as a function of `EmitVertex`, regardless of what data is actually written. Right?

How about XFB in vertex and tessellation shaders? 
> 
> Can you attach the sample .pipe + .spv files?

Sure. [issue.zip](https://github.com/GPUOpen-Drivers/llpc/files/9925518/issue.zip)

**Comment by amdrexu** [comment]
@nhaehnle I add you to the watcher list of an internal issue ticket. There, you can get more detailed context. The issue is also discussed in Khronos internally. The link is attached to the context mail thread in the issue ticket.

**Comment by nhaehnle** [comment]
Thank you for updating the issue description, and thank you for this additional context, I will take a look.

> How about XFB in vertex and tessellation shaders?

I believe the same logic applies: the counters should be incremented even if the output variable(s) are never written.

**Comment by nhaehnle** [comment]
I agree with your analysis, let's have a discussion about the right solution.

Looking at the provided sample, after SPIRV-to-LLVM translation we have roughly:
```llvm
@0 = external addrspace(64) global [1 x <4 x float>], !spirv.InOut !0
@1 = external addrspace(65) global <4 x float>, !spirv.InOut !1

; Function Attrs: nounwind
define dllexport spir_func void @main() #0 !spirv.ExecutionModel !2 !lgc.shaderstage !3 {
.entry:
  call spir_func void @EmitVertex() #0
  call void (...) @lgc.create.end.primitive(i32 0)
  ret void
}

!0 = !{{ i32, { i64, i64 }, i64, i64 } { i32 1, { i64, i64 } { i64 16908288, i64 0 }, i64 16908288, i64 16 }}
!1 = !{{ i64, i64 } { i64 4503603939246080, i64 0 }}
!2 = !{i32 3}
!3 = !{i32 4}
```
So, the output global variable is still there (`@1`), but the problem is that it's not referenced anywhere. This is different from the input SPIR-V, where the variable is referenced as part of the entry point interface:
```
               OpEntryPoint Geometry %4 "main" %12 %14
...
         %14 = OpVariable %_ptr_Output_v4float Output
```
It is allowed for SPIR-V modules to contain variables that are never referenced, and then those variables shouldn't factor into the XFB logic. Only the ones that are part of the `OpEntryPoint` should be considered.

So, the first step is for the SPIRVReader to preserve the required information by:

* Looking for an `OpExecutionMode Xfb`.
* If present, look at all global variables referenced by the relevant `OpEntryPoint`. Collect any in the `Output` storage class with an `XfbBuffer` decoration:
  > From section 26.1 (Transform Feedback) of the Vulkan 1.3.233 spec: "Outputs decorated with XfbBuffer will be written out to the corresponding transform feedback buffers bound to the command buffer when transform feedback is active."
* Preserve relevant information somehow.

For preserving the relevant information, my suggestion would be `!lgc.xfb.state` metadata, defined as follows:
```
lgc.xfb.state metadata = {
  i32 buffer0Stream, i32 buffer0Stride, i32 buffer1Stream, i32 buffer1Stride,
  i32 buffer2Stream, i32 buffer2Stride, i32 buffer3Stream, i32 buffer3Stride }
; buffer${i}Stream is the vertex StreamId that writes to buffer i, or -1 if that particular buffer is unused (e.g. StreamId in EmitVertex)
```
> The use of buffer${i}Stream variables here is justified by section 26.1 (Transform Feedback) of the Vulkan 1.3.233 spec: "All outputs assigned to a given transform feedback buffer are required to come from a single vertex stream."

In the sample pipeline, I expect that the GS function after SPIRV-to-LLVM translation is:
```llvm
define dllexport spir_func void @main() #0 !spirv.ExecutionModel !2 !lgc.shaderstage !3 !lgc.xfb.state !6 {
.entry:
  call spir_func void @EmitVertex() #0
  call void (...) @lgc.create.end.primitive(i32 0)
  ret void
}

...

; buffer 0 enabled from stream 0 with stride 16, other buffers disabled (stride values are ignored and could be anything)
!6 = !{i32 0, i32 16, i32 -1, i32 0, i32 -1, i32 0, i32 -1, i32 0}
```
No changes to llpcSpirvLowerGlobal are needed.

Later stages of the compiler in LGC refer to the metadata, for example in ConfigBuilder and PatchInOutImportExport.

We should remove the redundant Xfb-related information of `lgc::ResourceUsage::{enableXfb,xfbStrides,streamXfbBuffers}` and add helper methods for setting and getting this metadata in a convenient format. For example, checking `enableXfb` is replaced by checking whether the `!lgc.xfb.state` metadata is present.

How does this sound? It preserves the required information and helps us remove state from `lgc::ResourceUsage`, which is a long-term goal anyway, and avoids fake store instructions.

cc @trenouf for additional feedback on this proposed approach.

**Comment by xuechen417** [comment]
Hooray! Thank you for the proposed approach with detailed explanations! I will follow your proposal to implement.

**Comment by trenouf** [comment]
> What do you mean "a seprate explicit lgc call for writing xfb"? Is it different from current write.xfb.output?

That call writes the output itself and writes the xfb buffer, right? I was thinking we could have a separate call that just writes the xfb buffer, and the front-end would generate it even if there are no writes to the output. (Sorry if this makes no sense because I've forgotten some details of how it all works.)

**Comment by nhaehnle** [comment]
It feels to me like that would be a bigger change to truly make consistent with how the outputs are written, and it becomes harder to query the relevant data where needed. I'm thinking particularly of the ConfigBuilder.

**Comment by trenouf** [comment]
Agreed it would be a bigger change and we do not want to do that here.

**Comment by xuechen417** [comment]
Yes, it also involves a major change in the current input/output packing workflow. We may need a high-level design for "a seprate explicit lgc call for writing xfb".
