### ISSUE TITLE
dEQP-VK.graphicsfuzz.similar-nested-ifs

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#214]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[similar-nested-ifs.zip](https://github.com/GPUOpen-Drivers/llpc/files/3609734/similar-nested-ifs.zip)

**Comment by MarcinKantochAMD** [comment]
Hi Paul. I ran the test today on LLPC stack and it is passing.

**Comment by MarcinKantochAMD** [comment]
Sorry Paul. I was not aware that your issues relate to Debug build. I was testing with a Release build.

**Comment by paulthomson** [comment]
This still seems to fail.

**Comment by jayfoad** [comment]
I can reproduce this with upstream LLVM. Here's a test case:
```
diff --git a/llvm/test/CodeGen/AMDGPU/fold-multiple-operands.mir b/llvm/test/CodeGen/AMDGPU/fold-multiple-operands.mir
new file mode 100644
index 00000000000..bd406cb56ac
--- /dev/null
+++ b/llvm/test/CodeGen/AMDGPU/fold-multiple-operands.mir
@@ -0,0 +1,9 @@
+# RUN: llc -march=amdgcn -verify-machineinstrs -run-pass si-fold-operands %s -o - | FileCheck %s
+
+# CHECK: S_ADD_I32
+name: test
+body: |
+  bb.0:
+    %0:sreg_32 = S_MOV_B32 70
+    %1:sreg_32 = S_MOV_B32 80
+    %2:sreg_32 = S_ADD_I32 %0, %1, implicit-def $scc
```

**Comment by s-perron** [comment]
@jayfoad Were you working in a fix for this?

**Comment by s-perron** [comment]
The SIFoldOperands pass will propagate the constants into the Add instruction.  This add of two immediates will not be folded.  When trying to encode this instruction, it fails because there is no way to represent this instruction.

I do not know how this is suppose to be handled in LLVM or the amdgpu backend.  Is there a pass that is suppose to fix this up by pulling out one of the immediates into a register?  Is there a pass that is suppose to fold the add instruction?  Or should SIFoldOperands be changed to not create this instruction in the first place?

@trenouf Any suggestions?

**Comment by jayfoad** [comment]
As far as I know no-one is working on it yet. I'm not familiar with SIFoldOperands but I would assume it should not create the unencodable instruction in the first place.

**Comment by nhaehnle** [comment]
I'd argue that the best short-term fix is to avoid forming the un-encodable instruction and leaving a TODO, because -verify-instructions should flag the intermediate MIR as incorrect anyway.

Long run, we should have a proper MachineInstCombine infrastructure for MIR. My hope would be that we can grow this in connection to GlobalISel.

**Comment by dstutt** [comment]
I've got a fix in review for this - see https://reviews.llvm.org/D70896

**Comment by dstutt** [comment]
It's been submitted upstream.

**Comment by jayfoad** [comment]
Fixed by GPUOpen-Drivers/llvm-project@46db60683422180688bff0737142c343ba28e7cb

**Comment by kuhar** [comment]
We should add it to shaderdb; alongside the other fixed fuzzing issues.

**Comment by kuhar** [comment]
I created a PR adding this to shaderdb: #449.
