### ISSUE TITLE
Discussion about mesh shaders and GFX11

### ISSUE THREAD

**Issue by Venemo** [GPUOpen-Drivers/llpc#2295]
Hi,

Sebastian suggested to open an issue here to discuss about mesh shading with @amdrexu and @nhaehnle. I'd like to have a conversation about the LLPC code and mesh shading on GFX11. (For context, I work on mesh shading in RADV.)

#### Legacy fast launch vs. new fast launch

It looks like PAL and LLPC carry some code to still support the legacy fast launch mode `FAST_LAUNCH=1` on GFX11. Can I assume that the new `FAST_LAUNCH=2` always performs better or is there sometimes a reason to select the legacy mode?

Are there any features that only work in the legacy mode or the new mode?  
For example, would row exports work without fast launch?

#### LDS vs. attribute ring

Looking at the LLPC code, it still stores all mesh shader attributes to LDS and reloads them at the end before storing them to the attribute ring. I'm curious what is the rationale for this? Excessive LDS use can reduce the maximum wave count so I think it'd be better if they went straight to the attribute ring.

Also, how does LLPC handle the situation when there isn't enough LDS space to hold every attribute? In RADV we have a "mesh shader scratch ring" for this, which is IMO a very ugly solution and it'd be nice to know if there is a good alternative to that.

#### Per-primitive attributes

A comment in the code mentions that the HW always assumes that there is at least 1 per-vertex parameter even when `VS_EXPORT_COUNT` is zero and makes some effort to pad the per-primitive attribute locations. This makes me wonder, does this mean it's not possible to have 32 per-primitive params? How is that within spec?

Also... why wasn't this a problem on Navi 2? I think `VS_EXPORT_COUNT` works the same way there too.

#### Weird buffer_store bug

Lastly, here is a really weird one: I'm having trouble with `buffer_store` instructions without the `idxen` bit for storing to the attribute ring. For example, [this shader](https://pastebin.com/raw/s9bw1qy3) fails a test and [this other one](https://pastebin.com/raw/LYDuLN0E) passes (both printed with disabled VN and scheduling for easy comparability).

I think this:  
`buffer_store_b32 v1, off, s[16:19], s7`  
should be equivalent to this:  
`v_mov_b32_e32 v2, 0`  
`buffer_store_b32 v1, v2, s[16:19], s7 idxen`  
but apparently the first one fails and the second one passes the test, which doesn't make sense to me.

Looking at [this commit](https://github.com/GPUOpen-Drivers/llpc/commit/0e032888eb45af51515c57eca3498cc94f133a6e) the commit message mentions *"issues that may or may not be a hardware problem"* when trying to get rid of the index VGPR ― that sounds like the same problem, do you guys have any clue about it?

Thanks and best regards,
Timur

**Comment by nhaehnle** [comment]
Hi Timur,

I don't think there's ever a reason not to use the new fast launch. I think the code was left in case of errata, of which there weren't any? :)

I wanted us to look into how we write attributes as well, actually. When outputs aren't read back, pretty much the only reason to go via LDS is if you end up with a lot of partial cacheline writes otherwise. Of course, there could also be some weird higher-order cache effects, but those are a lost cause anyway. I'm not aware of any performance testing results.

About the per-primitive attribute question, honestly I just don't know, I don't have that level of detail paged in.

Finally, I don't know what it is you're trying to do exactly with those buffer_stores. There have always been cases where the hardware implicitly treated idxen with index 0 differently from idxoff, e.g. different bounds checking (probably going back all the way to SI...). It's the reason why we split buffer intrinsics in LLVM into `raw` vs. `struct` buffer intrinsics. It's annoying, but that part usually doesn't hurt. The comment you're referring to did indeed turn out to be a hardware issue in that add_tid_enable just doesn't work in the swizzle mode that's needed for the attribute ring :(

**Comment by Venemo** [comment]
Thanks for the reply Nicolai!

> I don't think there's ever a reason not to use the new fast launch. I think the code was left in case of errata, of which there weren't any? :)

That's great! I'm looking forward to bringing up the new mode!

> When outputs aren't read back, pretty much the only reason to go via LDS is if you end up with a lot of partial cacheline writes otherwise.

Sadly, I'm not aware of any relevant users of mesh shading, so it's hard to do any perf comparison. Maybe GravityMark, but that didn't look too relevant to be honest.

Partial cache line writes are a good point. In my implementation I decided to always store to the attribute ring except for attributes which also need `exp`, those still go through LDS.

> About the per-primitive attribute question, honestly I just don't know, I don't have that level of detail paged in.

No worries, maybe someone else remembers? The VK spec may lets us get away with it, at least I didn't get any CTS failures so I think it's okay.

> Finally, I don't know what it is you're trying to do exactly with those buffer_stores.

This comes from a CTS test which stores a mesh shader attribute by indexing the output array with a constant zero.

> There have always been cases where the hardware implicitly treated idxen with index 0 differently from idxoff, e.g. different bounds checking (probably going back all the way to SI...). It's the reason why we split buffer intrinsics in LLVM into raw vs. struct buffer intrinsics. It's annoying, but that part usually doesn't hurt.

I now took a brief look at the ISA docs. As far as I understand the bounds checking depends on the `OOB_SELECT` field and not the `idxen` bit. With `OOB_SELECT=0` the bounds check is described as:  
*(index >= NumRecords) || (offset+payload > stride)* and this doesn't mention the `idxen` bit so I would assume that with `idxen=0` this would be equivalent to as if *index* was zero. There must be a detail that I'm missing here, can you please elaborate?

**Comment by amdrexu** [comment]
Hi Timur,

Let me try to answer some of your questions:

> Are there any features that only work in the legacy mode or the new mode?
> For example, would row exports work without fast launch?

For GFX11, we always use new fast launch mode. The legacy mode is still supported. But PAL and CP both have some optimizations that only work in the new mode. Future HW might completely remove the legacy mode so it only works on GFX10.3. The row export has nothing to do with fast launch mode. It is supposed to work in both modes but we don't verify this.

> Looking at the LLPC code, it still stores all mesh shader attributes to LDS and reloads them at the end before storing them to the attribute ring. I'm curious what is the rationale for this?

Apart from what Nicolai said, we encountered some special cases. The API mesh shader uses small workgroup size (say `local_size_x=4, local_size_y=1, local_size_z=1`) but it exports large number of primitives and vertices (say `primitive_count = 128, vertex_count = 128`). In such case, if you don't cache the attributes and just use native threads of API mesh shader. The parallelism will be hurt.

We have the mesh shader capability flag `maxMeshOutputMemorySize` to make sure the LDS usage is within our expectation. As you said, we do have a design that use scratch memory to support exceeding LDS usage in our internal compiler. But since there are few benchmarks now, the necessity of this is unclear. And this backup mode is not verified.

> This makes me wonder, does this mean it's not possible to have 32 per-primitive params? How is that within spec?

This might be a HW design defect. On GFX10.3 (Navi21), HW has dedicated parameter cache to export attributes to PS with `exp` instruction. The attributes are sorted (the former are all vertex attributes and the latter are all primitive attributes). How to differentiate them is by the register field `SPI_PS_IN_CONTROL.NUM_PRIM_INTERP` and `SPI_PS_IN_CONTROL.NUM_INTERP`. If we set `SPI_PS_IN_CONTROL.NUM_INTERP = 0`, HW knows we don't have any vertex attributes even if `VS_EXPORT_COUNT=0` means there is one vertex attribute. So GFX10.3 could behaves correctly in primitive attribute mapping. But `SPI_PS_IN_CONTROL.NUM_PRIM_INTERP` is removed from GFX11 and all attributes are exported to attribute ring buffer. The HW logic is changed and relies on `VS_EXPORT_COUNT` and `PRIM_EXPORT_COUNT` so this issue comes out. Indeed, as you said, we can export 32 primitive attributes this time. There is a mesh shader capability `maxMeshOutputComponents`, which could control this and let App not use excessive per-primitive locations.

Hope my explanations are clear to you :)

**Comment by Venemo** [comment]
> The row export has nothing to do with fast launch mode. It is supposed to work in both modes but we don't verify this.

If row export works in other shaders too, could we use it to improve geometry shaders?

> The API mesh shader uses small workgroup size [...] but it exports large number of primitives and vertices [...] In such case, if you don't cache the attributes and just use native threads of API mesh shader. The parallelism will be hurt.

Thanks that's good to know. Maybe we can detect this case and fall back to using LDS if possible.

> We have the mesh shader capability flag maxMeshOutputMemorySize to make sure the LDS usage is within our expectation. 

As far as I know, the HW only allows to allocate 32K LDS to mesh shaders, or is that wrong?

> On GFX10.3 (Navi21), HW has dedicated parameter cache to export attributes to PS with exp instruction. The attributes are sorted (the former are all vertex attributes and the latter are all primitive attributes). How to differentiate them is by the register field SPI_PS_IN_CONTROL.NUM_PRIM_INTERP and SPI_PS_IN_CONTROL.NUM_INTERP. If we set SPI_PS_IN_CONTROL.NUM_INTERP = 0, HW knows we don't have any vertex attributes even if VS_EXPORT_COUNT=0 means there is one vertex attribute.

I am aware that `NUM_PRIM_INTERP` controls the per-prim attribute count in PS input interpolation, but I'm not sure that the GE uses that for the parameter cache allocation too.

**Comment by amdrexu** [comment]
> If row export works in other shaders too, could we use it to improve geometry shaders?

It has difficulties in practice. For row export, we use less vertex/primitive threads to export vertex/primitive. The row number is not equal to the wave ID necessarily. It is calculated by knowing the total mesh thread number at compilation time. And another important thing is that we don't rely on any info from system VGPR inputs of vertex/primitive. All such info is calculated in API mesh shader. But for geometry shader, some info is from system VGPR (such as primitive ID, GS instance ID, and the like). GE will invoke enough ES/GS threads to represent such info for each vertex/primitive. The row number calculation might be more complex. As the design doc said, HW row export is for mesh shader purposely.

> As far as I know, the HW only allows to allocate 32K LDS to mesh shaders, or is that wrong?

Only allow 16K.

**Comment by amdrexu** [comment]
> I am aware that NUM_PRIM_INTERP controls the per-prim attribute count in PS input interpolation, but I'm not sure that the GE uses that for the parameter cache allocation too.

Yes, the parameter cache is allocated according to `VS_EXPORT_COUNT` and `PRIM_EXPORT_COUNT`. The tricky thing is in PS interpolation. For GFX10.3, you export primitive attribute to `param0` and get it in PS from `attr0`. That is OK because HW use `NUM_PRIM_INTERP` to determine if this is a primitive attribute and applies per-primitive interpolation. It doesn't rely on `VS_EXPORT_COUNT`. On GFX11, the attribute ring is employed. HW still uses `VS_EXPORT_COUNT` and `PRIM_EXPORT_COUNT` to determine the attribute mapping in the ring, but it relies on such info to determine if an attribute in PS interpolation is per-primitive as well because of the lack of `NUM_PRIM_INTERP`. As a result, it applies per-vertex interpolation for location 0 and behaves wrongly. This issue is found in HW simulation codes so could be viewed as a defect. Previously, we had `NO_PC_EXPORT` to cancel `VS_EXPORT_COUNT=0` doesn't mean no vertex attribute. But with the introduction of primitive attributes, things are complicated.

**Comment by Venemo** [comment]
> Yes, the parameter cache is allocated according to VS_EXPORT_COUNT and PRIM_EXPORT_COUNT. The tricky thing is in PS interpolation. For GFX10.3, you export primitive attribute to param0 and get it in PS from attr0. That is OK because HW use NUM_PRIM_INTERP to determine if this is a primitive attribute and applies per-primitive interpolation.

Thanks! I understand how the PS interpolation works. I also understand how it's different on GFX11. But still not fully sure about `VS/PRIM_EXPORT_COUNT` on GFX10.3.

As far as I understand the parameter cache is allocated according to `VS_EXPORT_COUNT`, `PRIM_EXPORT_COUNT` and the number of vertices and primitives given to the `gs_alloc_req` and **not** according to the PS interpolation registers, is that correct? So, I think when `VS_EXPORT_COUNT=0` and `PRIM_EXPORT_COUNT=1` the `gs_alloc_req` will still allocate PC space for 1 per-vertex param and 1 per-primitive param, no?

**Comment by Venemo** [comment]
> Only allow 16K.

That is definitely not enough to implement the minimum requirements of the spec. `maxMeshSharedMemorySize` is minimum 28K and `maxMeshOutputMemorySize` is minimum 32K.

**Comment by amdrexu** [comment]
> is that correct? So, I think when VS_EXPORT_COUNT=0 and PRIM_EXPORT_COUNT=1 the gs_alloc_req will still allocate PC space for 1 per-vertex param and 1 per-primitive param, no?

Yes, you are right. According to the simulation codes, PC space will be allocated with 1 vertex attribute and 1 primitive attribute only according to `VS_EXPORT_COUNT` and `PRIM_EXPORT_COUNT`. This issue is caused by how PC treats the attribute as per-vertex or per-primitive in PS interpolation. PC does wrong interpolation on GFX11. I think the root cause is for traditional graphics shader, there is no concept of "per-primitive" attribute. For vertex processing stages, you either have no vertex attribute or have at least one vertex attribute. So HW doesn't take into account this special case that mesh shader could only have primitive attributes without vertex attribute.

> That is definitely not enough to implement the minimum requirements of the spec. maxMeshSharedMemorySize is minimum 28K and maxMeshOutputMemorySize is minimum 32K.

I see we set both capability values to 16K. I will check this with driver engineers tomorrow.

**Comment by Venemo** [comment]
> I see we set both capability values to 16K. I will check this with driver engineers tomorrow.

See the VK spec 46.1 Limit requirements, there is a required minimum value for both of those. This is done to ensure that D3D12 mesh shaders can be translated to Vulkan.

**Comment by amdrexu** [comment]
> See the VK spec 46.1 Limit requirements, there is a required minimum value for both of those. This is done to ensure that D3D12 mesh shaders can be translated to Vulkan.

Sorry. It is my misleading statement. I mean we can allocate 16K dwords not 16K bytes :) The byte size is 64K.

**Comment by Venemo** [comment]
> Sorry. It is my misleading statement. I mean we can allocate 16K dwords not 16K bytes :) The byte size is 64K.

Thank you! Understood. Then my info was outdated or incorrect. Does it work this way on old GPUs too? I thought that non-compute shader stages couldn't use the full 64K LDS, only half of it (32K).

**Comment by amdrexu** [comment]
> I thought that non-compute shader stages couldn't use the full 64K LDS, only half of it (32K).

As I know, we can only allocate 8K dwords on GFX6. From GFX7, the size is enlarged to 16K dwords according to register configuration spec.

**Comment by Venemo** [comment]
Thank you Rex for clarifying that!

**Comment by Venemo** [comment]
Can you guys elaborare more on that weird buffer store issue? I still don't see how bounds checking would affect that one.

**Comment by Venemo** [comment]
This specific case may be unlikely (though the CTS hits it), but that's okay. The problem isn't this case specifically, the problem is that this contradicts the ISA manual which means we don't understand why it doesn't work, which also means that we can't be fully sure whether other use cases are affected.

I personally suspect that swizzled buffer addressing may be buggy and just doesn't work correctly without the idxen bit, but I can't be sure.

**Comment by nhaehnle** [comment]
Yes, the ISA manual fails to mention this. Again, this is why LLVM has separate "raw" and "struct" intrinsics. If you want the index addressing features, you need the idxen bit.

**Comment by Venemo** [comment]
Thanks Nicolai! I'm sorry if this question is frustrating to you, and I appreciate your time helping us. I'm sure the answer is obvious to you but I really don't have any knowledge about this besides what is in the ISA docs.

Can you please say how it really works, and exactly what parts of the ISA docs is incorrect? What are the "indexed features"? According to the ISA doc, it simply multiplies the index VGPR with the stride (which is set in the descriptor) and adds the result to the address, and that's it. The doc says tha this is zero when the idxen bit is not set, which to me indicates that idxen=0 is the same as index=0 with idxen=1.

**Comment by nhaehnle** [comment]
The part about it being 0 without idxen is probably just a historical leftover that hasn't been updated.

**Comment by Venemo** [comment]
Both the RDNA3 ISA chapter 9.4 and the original Southern Islands ISA chapter 8.1.5 describe the address calculation like below:

```
ADDRESS = const_base + sgpr_offset + buffer_offset
buffer_offset = Offset + const_stride * Index
Offset = (inst_offen ? vgpr_offset : 0) + inst_offset
Index = (inst_idxen ? vgpr_index : 0) + (const_add_tid_enable ? workitem_id : 0)
```

From what you're saying, I gather that you are referring to this part: `(inst_idxen ? vgpr_index : 0)` ― if this is incorrect can you say what is the correct version? Also, has it always been incorrect or did it change on GFX11? I'm pretty sure we've successfully used swizzled buffers on GFX6-8 with idxen=0 without issue (for the ESGS and GSVS rings).

**Comment by nhaehnle** [comment]
The correct version is that the entire formula doesn't apply when both add_tid_enable and idxen are off. You shouldn't enable both at the same time, and when you follow that rule it's just `index = idxen ? vgpr_index : workitem_id`.

I don't remember when exactly this changed. Probably around the gfx9/gfx10 time frame.

**Comment by Venemo** [comment]
We don't use add_tid_enable so this doesn't explain the problematic instruction above.
