### ISSUE TITLE
dEQP-VK.graphicsfuzz.return-float-from-while-loop

### ISSUE THREAD

**Issue by paulthomson** [GPUOpen-Drivers/llpc#332]
This test fails. To reproduce: `amdllpc -gfxip=9.0.0 -verify-ir -o temp.out *.spv`

[return-float-from-while-loop.zip](https://github.com/GPUOpen-Drivers/llpc/files/3833406/return-float-from-while-loop.zip)

**Comment by nhaehnle** [comment]
Hi Paul, aside from the fact that this is probably not a bug on the latest dev branch based on discussions on other bugs, I'd also ask you in the future to take a step back and produce higher quality bug reports.

For instance, **how** does the test fail? Does it hit an assertion or other error in the compiler? Does it generate incorrect code? Since when do these failures occur? (CTS tests are usually passing since CTS testing is performed regularly, so you should be able to find a regression point.)

Furthermore, shotgunning lots of issues like you did helps nobody. Once you've collected more information such as suggested in the previous paragraph, you will most likely find that many or even all of the issues are likely to have the same root cause (for example, they fail to compile with the same error message). It is then better to open a single issue with that error message as the title, and provide a mention of the various CTS failures that exhibit the problem in the issue body. Thank you!

**Comment by paulthomson** [comment]
Apologies for the poor quality bug reports; I was indeed being slightly lazy here, as the process is not automated. Apart from not providing the log, I also forgot to add that I was using a debug build of amdllpc when running these tests.

We are occasionally fuzzing amdllpc and creating dEQP test cases that expose the issues. The tests will always start with `dEQP-VK.graphicsfuzz.`. But we fuzz and add tests for many tools and devices other than LLPC.

If you are indeed testing the Khronos dEQP Gerrit master branch (and perhaps pending CLs) on the debug build of the dev branch of the AMDVLK driver, then there is probably no point in me reporting these. However, I believe the debug build was possibly not being used in the past and so certain assertion failures were being missed, but perhaps this has changed.

Apologies also for creating one issue per test; other projects requested that we do this, but if you are running the tests, you will see the failures eventually anyway.

Can I ask: what is the best way to test the latest version of LLPC? Is building the dev branch of AMDVLK a fairly good approach? Is there a large delay between AMDVLK being updated to use the latest dev branch commit of LLPC? Also, feel free to let me know if assertion failures in the debug build should indeed be treated as bugs; if not, I can just use the release build.

**Comment by nhaehnle** [comment]
I think bug reports in general are fine, as things do slip through cracks... for example, I believe our internal automatic testing currently doesn't have LLPC/LLVM assertions enabled (let alone runnign with anything like address sanitizer...). And thank you for the fuzzing!

Assertion failures in the compiler should absolutely be treated as bugs. Otherwise we'll just go mad over time ;)

> Can I ask: what is the best way to test the latest version of LLPC? Is building the dev branch of AMDVLK a fairly good approach? Is there a large delay between AMDVLK being updated to use the latest dev branch commit of LLPC?

I'll have to punt to @amdrexu @linqun @trenouf on some of the details here. I suspect it's fine to use the dev branch of AMDVLK but manually track the LLPC dev branch. That really ought to work reasonably fine, and if it doesn't, we should think about how to improve the situation.

**Comment by amdrexu** [comment]
I think building latest AMDVLK dev plus latest LLPC dev is enough. LLPC has versioning mechanism. Latest LLPC can work with not-latest AMDVLK.

**Comment by paulthomson** [comment]
Thanks!

**Comment by paulthomson** [comment]
Closing as this apparently does not reproduce.

**Comment by kuhar** [comment]
Sidenote: this does not validate:
```
ERROR: Fails to validate SPIR-V: 
error: 69: block <ID> 100[%100] exits the selection headed by <ID> 91[%91], but not via a structured exit
  %100 = OpLabel
```

**Comment by paulthomson** [comment]
Ah this now makes sense. The failures were all validation "errors" from the old, internal version of spirv-val. The shaders validate with a newer version of spirv-val.

I could disable validation when I run amdllpc, but I chose to leave the validation on so that we would still see these "failures" and to give an incentive to update the validator version in AMDVLK. I guess the shaders won't actually be validated at run time though?

**Comment by kuhar** [comment]
> I could disable validation when I run amdllpc, but I chose to leave the validation on so that we would still see these "failures" and to give an incentive to update the validator version in AMDVLK. I guess the shaders won't actually be validated at run time though?

IMO it would make sense to report inputs that pass spirv-val but crash llpc with assertions/sanitizers enabled. I suppose that in real-life scenarios all shaders are known ahead of time and can be validated offline.

**Comment by paulthomson** [comment]
Yeah, makes sense.

E.g.

```
$ amdllpc discard-continue-return.variant_fragment_shader.frag.spv
ERROR: Fails to validate SPIR-V: 
error: 67: block <ID> 34[%34] exits the selection headed by <ID> 35[%35], but not via a structured exit
  %34 = OpLabel


ERROR: 
=====  AMDLLPC FAILED  =====

```

vs.

```
$ amdllpc -val=false discard-continue-return.variant_fragment_shader.frag.spv
```

The old, buggy version of spirv-val is always run for me unless I pass `-val=false`. I will add `-val=false` from now on.

**Comment by amdrexu** [comment]
I think you can use latest codes of SPIRV-tools and build a spirv-val. Try it and if the error still exists we might report an issue ticket on SPIRV-tools repo. If the issue is gone, we will update imported SPIRV-tools source codes in spvgen.
