### ISSUE TITLE
Cache creator tool

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#431]
# Problem description

Compiling shaders when a game is running can be time consuming, and lowers the quality of the game.  This can be because of long wait times when a level starts or, much worse, hitching during game play.  One of the solutions to this is to create a cache of precompiled pipelines or shaders.  Then much less work needs to be done while the game is running.

This leads to a second problem.  How do we create the cache?  For some games, building the cache as people play the game does not work.  Developers are not able to see how their game will perform as they are developing it.  This would be a time consuming process that does not scale well, especially when the developers have a large number of shaders that are only run under very specific situations.

In this document, we propose a tool which we will call the “LLPC cache creator”.  This will be a tool that will create a shader cache that can be used by LLPC without running the application.  The input to the tool will be the Spir-V for the shaders and a few other options like the architecture.  It will write a cache to disk that could be passed to LLPC.

# Developer workflow

Developers write the shaders for their game.  Those will be given to the cache creator to produce the cache for LLPC with appropriate inputs.  Once the cache is available this is a file that could be loaded and passed to `vkCreatePipelineCache`.

The developer will not have to run their game to prime the cache, but this is accomplished offline.

# Requirements

*   The shader cache that is built does not require running the game.
*   The input is
    *   Spir-v binaries
    *   The gpu architecture to target
    *   Possible values for spec constants
    *   Possible formats for images, samplers, frame buffers, etc.
*   The output is a shader cache that can be used by LLPC
*   Initially, the shader cache will have a 100% hit rate for
    *   Compute pipelines meeting the constraints of the inputs
    *   Graphics pipelines composed of just a vertex shader and a fragment shader meeting the constraints of the inputs.
*   On average, the runtime of the generated code when using the cache must not be more than 5% worse than the code generated by doing a full compile.
*   On average, the cache hit time must be no more than 20% of the cache hit time of the current implementation.
*   The size of the shader cache cannot be larger than the size of the cache generated by the current implementation.
*   The tool must run in a generic Linux, even if an AMD GPU is not available.

# Relocatable shader elf

The cache creator tool has to build a cache that cover cases that may never come up.  This increases the size of the cache.  We need ways of implementing the cache that will reduce the size in order to meet the requirement that the cache will not increase in size.  This will be accomplished by compiling CS, VS, and PS shaders into individual **relocatable shader elf files** that can be reused in multiple pipelines.  These elf files will be stored in the cache in place of the current full pipeline elf files.

The relocatable elf will be able to be linked in 5 stages:

* Apply relocations to the `.rel.text` section of the relocatable elf files using information from the pipeline create info.
* Append the updated `.text` sections to form the new `.text` section. 
* Pick the symbols from the symbol tables of the relocatable elf with updates offsets.
* Merge the data in the `.note` sections of the relocatable elf and the pipeline create info.
* Merge other sections by appends the data from one to the other.

# Constructing relocatable shader elf

The exact content of a relocatable shader elf file will have to classify every piece of data in that appears in a `.pipe` file must be classified into one of the following categories:

* Relocatable: This piece of information can be replaced by a relocation in `.text` section and can be fixed up when linking relocatable shader elf.  These values will not need to be included in the hash for the cache.
* Patchable: This piece of information does not effect the `.text`, but only the `.note` section.  The `.note` can be updated at link time.  These values will not need to be included in the hash for the cache.
* Determinable:  This piece of information has to match data in the spir-v, and can have only a single value.  It will not be handled in any special way.  These values will be included in the hash for the cache, but are not strictly needed.
* Bounded: This is information that has a finite range of possible values.  These values must be included in the hash for the cache.
* Unbounded: This is information that could take on an infinite number (or very large) number of values.  There is no special handling for these values when creating a relocatable elf.  They must be part of the hash for the cache.

Attached is a first pass at how each value could be handled: [pipeline state - Sheet1 (1).pdf](https://github.com/GPUOpen-Drivers/llpc/files/4078592/pipeline.state.-.Sheet1.1.pdf)

# Cache creator tool

The cache creator tool will be incorporated into the `amdllpc` tools as an options.  For each spir-v file that it is given, it will construct all possible pipeline build infos for it and build the relocatable elf for with that pipeline build info, caching them as it goes along.

The cache creator tool will handle each type of value in the build info in kind:

* Relocatable: The specific values does not matter since it will not be used.  A single default value will be used.
* Patchable:  Like relocatable values, a default value will be used.
* Determinable: The spir-v will be parsed to find the single possible value, and that value will be used.
* Bounded: The cache creator tools will create relocatable shader elf for each possible value.
* Unbounded:  The user will have to provide a set of possible values as an input to the cache creator tools, and the cache creator tool will build relocatable elf for each possible value.

Note that the combinations will build on each other.  Say, there are two bounded values with 2 values each and two unbounded values where the user value 3 possible values, then a total of `2*2*3*3=36` relocatable elf version will be generated.

To further reduce the number of combinations, we will have to classify which members of the pipeline create info are used by which shader types.

**Comment by linqun** [comment]
1. I think we can reuse some code for partial pipeline compile. @amingriyue (David Zhou) is working on it.
2. for partial pipeline compile, we only consider the fragment shader and compute shader. for vertex shader, many graphic states and vertex buffer state will affect the compile result. so I am afraid it is not very easy or friendly to do it in offline time.
3.  in partial pipeline compile, we plan to remove the offset of root resource node in hash, and patch the offset in real pipeline compile, I suppose it is match your "Patchable" type.
4. until now, amdllpc can't access pipeline binary cache, it only can output ELF binary, I suppose we will have other tools to merge multiple ELF binary into pipeline binary cache.
5. which data do you want to be relocatable? the offset of resource bindings? or something else?

**Comment by kuhar** [comment]
Hi @linqun and @amingriyue,

I found a description of `partial pipeline compile` in `docs/LlpcOverview.md`:

```
### Partial pipeline caching

There is a facility for caching part of a graphics pipeline. Where the whole pipeline missed
the cache, this works by dividing the pipeline into the vertex-processing part (all shaders
except FS), and the fragment-processing part (the FS), in the hope that one or the other part
has been used in a previous pipeline.

The hash used for the cache needs to include information on how final-vertex-stage outputs
(for a vertex-processing part) or fragment shader inputs (for an FS) are mapped. This mapping
is part of the middle-end. When calling the middle-end with `Pipeline::Generate`, the front-end
passes it a `CheckShaderCacheFunc` lambda. Once it has done the input/output mapping, the
middle-end calls this lambda back with per-shader-stage hashes of input/output mapping, allowing
the front-end to decide whether it has a cache hit and does not need to compile one or other of
the two parts of the pipeline. If it has a cache hit, it returns the shader stage mask with the
shader stages from the cache hit part zeroed out, so that part is not compiled any further.

The result of that is still an ELF in the normal way. The front-end then combines the ELF it found
in the cache with the ELF from this compile.
```

Could you point me to the main files / classes / functions related to partial pipeline compiling/caching? Which part of it is David currently working on? I think it would be useful for a future reference.

Thanks,
Jakub

**Comment by linqun** [comment]
We will prepare a MD file for partial pipeline caching in following couple days.
Following is the working flow and status of partial pipeline compile:
- collect resource usage in ICompiler::BuildShaderModule (done)
- build pipeline layout according to resource usage + some special rules (partial done)
- build pipeline state according to inout  type + some special rules (partial done)
- call  ICompiler::BuildGraphicsPipeline/BuildComputePipeline to build pipeline, it is only to modify shader cache, the return value is ignored. 
  a) we need generate special hash when store it in shader cache. David is working on it now.

All above operations are done in vkCreateShaderModule, and the special rules will be decided according to app profile result, i.e. we plan to enable partial pipeline based on app profile.

**Comment by nhaehnle** [comment]
The overall plan sounds good to me. A couple of notes:

1. Ideally, this would integrate well not just with amdllpc for ahead-of-time use, but also with runtime use, i.e. on vkCreateShaderModule. Relocations should allow us to avoid a lot of what's currently done in the partial pipeline compile for building the pipeline layout.

2. For data that is classified "Determinable", even the regular pipeline compile path should have assertions to verify that the piece of data given by the pipeline options is in fact identical to the one that would have been determined. This gives you some assurance against bit rot of the determination logic.

3. attribute[x].format could be made largely relocatable, by having new relocation types to patch the format field of tbuffer_load_format instructions. This isn't fully sufficient, because some hardware needs extra ALU fixups e.g. for rgb10a2 formats, but it would allow you to bucket compiles into "normal" and "few special cases". If you look at what radeonsi does for vertex buffer formats, around the si_vertex_elements structure, you'll see some of that. [si_create_vertex_elements](https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/gallium/drivers/radeonsi/si_state.c#L4857) is a reasonable starting point. [radeonsi effectively "relocates" the format by using buffer_load_format instructions which take the format from the resource descriptor; Vulkan prefers tbuffer_load_format since it's more convenient with how SoA vertex array layouts work there]

4. binding[x].binding is where the vertex buffer descriptor should be loaded from, similar to descriptor set layouts. This may be relocatable, if the driver doesn't rearrange those for us in the first place when it prepares the vertex buffer descriptors, something to check...

5. binding[x].inputRate is whether a vertex input is per-vertex or per-instance. This is... not really relocatable in the traditional sense, though since both values are in a VGPR maybe some relocations could be hacked there with a new relocation type that patches a "VGPR source operand" field? It'd get ugly, but it's possible...

6. binding[x].stride should really be part of the vertex buffer descriptor, so should not affect shader compilation at all.

7. colorBuffer[x].blendEnable and colorBuffer[x].blendSrcAlphaToColor should only be relevant for RB+ hardware register setup and not affect shader compilation.

8. colorBuffer[x].channelWriteMask should not affect shader compilation, except as an optimization that allows dead-code elimination. Put differently, you can always set that to 0xf without affecting correctness.

9. cullMode, frontFace, topology should only be relevant for NGG with in-shader culling.

10. depthBiasEnable, depthClipEnable, disableVertexReuse, dualSourceBlendEnable: I believe those only affect hardware register state and not shader compilation

11. entryPoint: you'll want to be able to compile multiple shaders though...

12. options: You should probably just always leave those at a default for what you're trying to do. Or deal with the complicated mess that results if you don't, but at least for the runtime-version of this I'd rather not have to deal with it...

**Comment by amdrexu** [comment]
disableVertexReuse is something special from one of my changes: https://github.com/GPUOpen-Drivers/llpc/pull/421. The GS instancing requires larger ES-GS ring size (because ES emits more vertices) for pre-GFX10 GPUs when vertex reuse has to be turned off. So this field has impacts on both register settings and shader compilation. But this caching plan is aimed at VS-FS pipeline currently, so it is not influenced.

**Comment by trenouf** [comment]
Hi Steven

How are you intending to handle specialization constants?

There might be some cases where you could use a reloc, if the constant is used as a value in a calculation or something. But the general case is that a specialization can be used anywhere a constant can be, right? Which includes things like the size of an array type, which can't be handled by a reloc.

I think there is a mechanism for a specialization constant to take a default value if it isn't otherwise supplied. But you don't know if it is going to be supplied until pipeline compilation time.

I guess one solution would be for the spir-v reader to spot that you're using a specialization constant in a way it can't express as a reloc, and return an error. Such a shader would not be pre-cacheable.

-tpr

**Comment by trenouf** [comment]
Or: When the spir-v reader sees a use of a specialization constant that cannot be expressed as a reloc (e.g. the size of an array type), then it uses the default value in the spir-v, and somehow records that it used that default value. Then, the linker needs to ensure that matches up with the corresponding specialization constant if specified.

**Comment by s-perron** [comment]
In general, spec constants are rarely used.  My plan was to initially just punt.  The idea would be that the spec constants are part of the hash, so if someone provides values for the spec constants that have not been seen before then we have to recompile.

If needed, we could look into relocations or allowing them as inputs to the cache creator tool.  Figuring out that part is low priority for now.

**Comment by nhaehnle** [comment]
I think for the general desktop use case we want to encourage use of specialization constants, so it is something we ought to think about. My understanding is that some engines with fancy shader authoring tools have an explosion of shaders causing the occasional stutter that would be much more manageable with them.

Apparently we don't even do the initial shader module compilation today when specialization constants are present. Arguably that's something we should fix, representing specialization constants as IR constants in some way, but of course that comes with a whole can of worms due to specialization constants in types...

At least the cases with specialization constants not in types should be possible to handle though, by turning them into an appropriate intrinsic during SPIR-V reading. This intrinsic can then either be replaced by the specialized value during pipeline compile, or it can be turned into a relocation for relocatable compiles.

**Comment by s-perron** [comment]
Done.
