### ISSUE TITLE
Shader compilation and specialization constants proposal

### ISSUE THREAD

**Issue by trenouf** [GPUOpen-Drivers/llpc#693]
Shader compilation and specialization constants proposal
=============================

If we're going to be able to deal with specialization constants with shader compilation and linking, then we need some scheme of dealing with them with relocs.

A use of a specialization constant falls into one of two different categories:
1. A normal use of a constant in an instruction or initializer, that can be changed with a reloc.
2. A use in something that cannot be changed after compilation with a reloc, such as the size of an array type. For this category, we can cope if that constant is not specified in the pipeline state (so it just takes its default value in the SPIR-V). Maybe we also want to be able to cope if it is specified to have the same value as the default. We cannot cope if it is specified to have a different value.

Front-end (SPIR-V reader)
---------------

For a category 1 constant use, the SPIR-V reader should call Builder::CreateRelocConstant (which already exists), with a name that specifies that it is a specialization constant, its number, which part of it, and its default value.

CreateRelocConstant can only cope with i32. For anything else, the SPIR-V reader will have to split it up and/or bitcast it.

For a category 2 constant use, the SPIR-V reader will call a new Builder call that we haven't invented yet, that says "this is an unchangeable specialization constant" with the same name specification as above.

Middle-end (LGC)
-------------

For a category 2 constant use, LGC needs to put the unchangeable specialization constant into the ELF in some way. Maybe it could use an LGC-private section in PAL metadata, but, for uniformity in handling the two categories of constant, I think I prefer the idea of a global variable that contains these unchangeable constants with relocs.

Linker
-----

The linker gets provided with the specialization constants in pipeline state. It uses those to resolve the specialization constant relocs above.

A reloc for a specialization constant that is not provided uses the default value encoded in the symbol name.

When processing a reloc in the global variable for unchangeable constants, and it would change the value from default, then it returns a recoverable error so we do a full pipeline compilation instead.

Possibly we could spot the failure case earlier, by spotting that the SPIR-V contains category 2 specialization constants. That might fail unnecessarily if the pipeline state doesn't actually set the constant, but that could be worth the saving in double compiles.

**Comment by nhaehnle** [comment]
This sounds good to me at a high level. Some notes:

I think unchangeable specialization constants can be emitted as a global symbol with appropriate linkage already in the builder. The linkage should probably be `weak` (the compiler cannot discard the symbol since it acts as a semantics-affecting marker, but it can be overridden with a different value during linking). To do this exactly in line with the relocations logic, the symbol shouldn't have any associated space in the ELF -- it should just have a value identical to the specialization constant's default. Not sure off the top of my head how to do that in LLVM.

When compiling a shader as part of a true pipeline compile (i.e., not the offline precompilation), then the SPIR-V reader should just use the pipeline-state-provided specialization value rather than the default. This should avoid the double compile during fallback that you mention.

Trying to spot category 2 specialization constants in SPIR-V is probably not worth it. First of all, specialization constants aren't used much in practice today in the first place. Second, we should consider supporting them properly in LLVM as the better long-term option.
