### ISSUE TITLE
Support loading multiPlane image descriptor

### ISSUE THREAD

**Issue by jiaxie-amd** [GPUOpen-Drivers/llpc#760]
As for supporting multiplane image descriptor loading, upload the following pipeline dump file for compiler implementation reference:
[SpvPipelineMultiPlane.zip](https://github.com/GPUOpen-Drivers/llpc/files/4763143/SpvPipelineMultiPlane.zip)

The multiplane image contains an immutalbe sampler and no more than 3 planes, each plane contains 8 DWords for resource descriptor.

I listed the following diagram of descriptor sets for all the cases.

- [x] A binding with array N which contains 1 plane image:

- descriptorRangeValue.arraySize = N
- node.type = DescriptorYCbCrSampler
- node.sizeInDwords = 8 * N

- [x] A binding with array N which contains 2 plane image:

- descriptorRangeValue.arraySize = N
- node.type = DescriptorYCbCrSampler
- node.sizeInDwords = 16 * N

- [x] A binding with array N which contains 3 plane image:

- descriptorRangeValue.arraySize = N
- node.type = DescriptorYCbCrSampler
- node.sizeInDwords = 24 * N

Normally, the
-  node.sizeInDwords = resourceDescSizeInDwords * M * N (M means plane count)

The loaded descriptors for each plane should be fetchable in ImageBuilder::CreateImageSampleConvert().

**Comment by nhaehnle** [comment]
I've now had the chance to look at this in a bit more detail, and my feeling is that in order to support this descriptor set layout, we should move away from the current model of:

> `@lgc.{create.}image.sample` intrinsic takes `8 x i32` and `4 x i32` descriptors and those descriptors are returned by `@lgc.{create.}load.desc.from.ptr`

toward a model where:

> `@lgc.{create.}image.sample` intrinsic takes a "fat descriptor pointer", and the load of the descriptor is inserted when lowering that intrinsic to amdgcn intrinsics.

The meaning of "fat descriptor" pointer remains unchanged: they are structs of `{ pointer, stride }`.

With this redesign, the lowering of `@lgc.image.sample` can then load the correct number of per-plane image descriptors from the provided pointer.

Cc @trenouf

**Comment by jiaxie-amd** [comment]
> I've now had the chance to look at this in a bit more detail

Hi Nicolai, Can you estimaate how long could this task be completed, I'm asking because the writing multiplane image descriptor support is very important in our recent plan (gating task).

**Comment by trenouf** [comment]
Hi Harris

Why do we need three descriptors? Can we find some way to use a single descriptor, then derive the stride between planes from somewhere else? E.g. a new field in the immutable sampler?

If that is not possible:

Nicolai, I guess your proposal will work. But I think it is a shame to have to do that just for the benefit of this Vulkan extension, which suffers from being badly specified due to not having a SPIR-V extension, so you can't tell what is happening at the SPIR-V level.

I am now thinking that it is a bad idea to have any handling of DescriptorYCbCrSampler in LGC at all, as it is a Vulkan driver specific thing. PAL and our internal middle-end compiler do not know about it. (The descriptor bit twiddling should stay in LGC, as that is gfxip-specific.)

So I am trying to think of a way of handling DescriptorYCbCrSampler in the SPIR-V reader and/or a lowering pass, and then we have a Builder::CreateConvertingImageSample into which you pass the up to three DescriptorResource (image) descriptors.

The difficulties are:

* If we try and handle it completely in the SPIR-V reader, then the already-existing problem that we can't see a converting descriptor through a phi node gets worse, in that we then can't see a converting descriptor through a not-yet-inlined call.
* If we try and handle it in a front-end pass (after inlining), it is made tricky by wanting to maintain the Builder abstraction, in which the front-end can choose whether to use BuilderRecorder or direct BuilderImpl.

I'll have more of a think about that.

**Comment by jiaxie-amd** [comment]
[AMD Official Use Only - Internal Distribution Only]

Hi Tim,


  *   Looks like the multi descriptors is a concept spec thought we should take it, for that spec mentioned:
combinedImageSamplerDescriptorCount is the number of combined image sampler descriptors that the implementation uses to access the format.
combinedImageSamplerDescriptorCount is a number between 1 and the number of planes in the format. A descriptor set layout binding with immutable Y′CBCR conversion samplers will have a maximum combinedImageSamplerDescriptorCount which is the maximum across all formats supported by its samplers of the combinedImageSamplerDescriptorCount for each format. Descriptor sets with that layout will internally use that maximum combinedImageSamplerDescriptorCount descriptors for each descriptor in the binding. This expanded number of descriptors will be consumed from the descriptor pool when a descriptor set is allocated, and counts towards the maxDescriptorSetSamplers, maxDescriptorSetSampledImages, maxPerStageDescriptorSamplers, and maxPerStageDescriptorSampledImages limits.
Note
All descriptors in a binding use the same maximum combinedImageSamplerDescriptorCount descriptors to allow implementations to use a
uniform stride for dynamic indexing of the descriptors in the binding. For example, consider a descriptor set layout binding with two descriptors and immutable samplers for multi-planar formats that have VkSamplerYcbcrConversionImageFormatProperties::combinedImageSamplerDescriptorCount values of 2 and 3 respectively. There are two descriptors in the binding and the maximum combinedImageSamplerDescriptorCount is 3, so descriptor sets with this layout consume 6 descriptors from the descriptor pool. To create a descriptor pool that allows allocating four descriptor sets with this layout, descriptorCount must be at least 24.



  *   And it is also a concept in pal for the multiplane image (which has multi sub-resource, each sub-resource has distinct resource descriptor), pal offers interface for us to generate multi sub-resources one time.


  *   Regarding to the rest of your concerns, especially the phi node part, I think the spec also aware that, for that I found it says:
If the combined image sampler enables sampler Y′CBCR conversion, it must be indexed only by constant integral expressions when aggregated into arrays in shader code, irrespective of the shaderSampledImageArrayDynamicIndexing feature.
So, I think it is acceptable and just treat it special in our compiler, or you can bother the spec, but what we’re doing here is somehow what spec expected.

Best Regards,
Harris

**Comment by jiaxie-amd** [comment]
* Looks like the multi descriptors is a concept spec thought we should take it, for that spec mentioned:

> combinedImageSamplerDescriptorCount is the number of combined image sampler descriptors that the implementation uses to access the format.
combinedImageSamplerDescriptorCount is a number between 1 and the number of planes in the format. A descriptor set layout binding with immutable Y′CBCR conversion samplers will have a maximum combinedImageSamplerDescriptorCount which is the maximum across all formats supported by its samplers of the combinedImageSamplerDescriptorCount for each format. Descriptor sets with that layout will internally use that maximum combinedImageSamplerDescriptorCount descriptors for each descriptor in the binding. This expanded number of descriptors will be consumed from the descriptor pool when a descriptor set is allocated, and counts towards the maxDescriptorSetSamplers, maxDescriptorSetSampledImages, maxPerStageDescriptorSamplers, and maxPerStageDescriptorSampledImages limits.
Note
All descriptors in a binding use the same maximum combinedImageSamplerDescriptorCount descriptors to allow implementations to use a
uniform stride for dynamic indexing of the descriptors in the binding. For example, consider a descriptor set layout binding with two descriptors and immutable samplers for multi-planar formats that have VkSamplerYcbcrConversionImageFormatProperties::combinedImageSamplerDescriptorCount values of 2 and 3 respectively. There are two descriptors in the binding and the maximum combinedImageSamplerDescriptorCount is 3, so descriptor sets with this layout consume 6 descriptors from the descriptor pool. To create a descriptor pool that allows allocating four descriptor sets with this layout, descriptorCount must be at least 24.

* A new feild in immutable sampler is not accecptable, which leads to the pipeline can not be reused and will lead to multiplane format with disjoint image's implementation being impossible.

* And it is also a concept in pal for the multiplane image (which has multi sub-resource, each sub-resource has distinct resource descriptor), pal offers interface for us to generate multi sub-resources one time.

* Regarding to the rest of your concerns, especially the phi node part, I think the spec also aware that, for that I found it says:

> If the combined image sampler enables sampler Y′CBCR conversion, it must be indexed only by constant integral expressions when aggregated into arrays in shader code, irrespective of the shaderSampledImageArrayDynamicIndexing feature.

So, I think it is acceptable and just treat it special in our compiler, or you can bother the spec, but what we’re doing here is somehow what spec expected.

**Comment by nhaehnle** [comment]
I'd prefer to keep the YCbCr code in LGC. The bulk of it is concerned with format conversion and sampling specific that should be API-agnostic.

Maybe the weirdness of how the descriptors work is API-specific and shouldn't be done in LGC, but that would still leave the question of how to represent those "extended descriptors" in the LGC intrinsics.

I'm also not sure that the descriptor weirdness is *entirely* API-specific. It does sound like having distinct resource descriptors is an inherently PAL aspect of this. So I don't think we should jump through hoops just to avoid the potential(!) risk of having a `YCbCrDescriptorKind::{Vulkan, DX12}` enum in LGC at some point in the future. If there's a clean and perfectly natural answer outside of LGC, then sure, let's go for that, but I'm not optimistic that this can be done, due to those phi- and function call-concerns.

**Comment by trenouf** [comment]
I agree we need to keep the descriptor bit-twiddling, and the actual conversion code, in LGC.

As for the rest of it:

I’m in the middle of trying out a change in which the whole problem is confined to the spir-v reader. We have to give a list of the converting samplers to the spir-v reader, which breaks the notion that the spir-v reader (and whole front-end) doesn’t need to know anything about resources. But that’s what Bil does. (We were already in the position that we can’t do early compilation to ELF with relocs when converting samplers are in use.)

Similar to the way that the spir-v reader encodes a descriptor pointer as {descptr, stride}, because we don’t know the stride at that point, I am adding code to encode a pointer to sampler or a sampler as a struct containing the (pointer to) sampler, plus a “converting sampler index”, which can be determined from the descset and binding at the time we first construct the pointer, and then carried through index and load operations.

When we get to the OpImageSample, in any sensible case we will be able to look through extractvalue/insertvalue chains and statically determine the converting sampler index, which tells us (a) whether it is a converting sampler, and (b) which one.

In a non-sensible case, we will not be able to statically determine the converting sampler index, so we will have to do the non-converting image sample and all possible image samples, and use a bunch of selects to dynamically get the right one. The non-sensible case is where the OpImageSample is inside a subfunction, so later inlining and optimization will make most of that extra code disappear in a puff of smoke.

To handle the planes, I will need to change the spir-v reader representation of an image descriptor to be an array of three image descriptors. In a non-converting-sampler-using program, two of the elements are always undef. In a converting-sample-using program, it will actually load three descriptors, but ones that turn out to be unused will again be optimized out.

Because we always inline, I think we can be confident that that optimizing out will happen, and we won’t have an unused descriptor load that loads off the end of the descriptor table left over in the final ISA.

**Comment by nhaehnle** [comment]
I feel like all of this would be quite a bit simpler if we just created the LLVM-IR-style descriptor load in the same place as the LLVM-IR-style image sample intrinsic and let CSE do the rest. This is what Mesa does.

**Comment by trenouf** [comment]
Hi Harris. I have some proposed commits for this in #782.

With those commits, CreateImageSampleConvert then gets called with an array of 3 image descriptors, and you can use however many of them your "number of planes" bitfield tells you to use. You should be able to rebase your change on top of that, and not need to insert any of your own descriptor loads in the middle of ImageBuilder.

My commits remain in the old state that the stride of a YCbCrSampler is 12 dwords, and I think you want to change it to 8*planes dwords. The stride is now set in llpc/context/llpcPipelineContext.cpp where the LLPC front-end is setting up the user data layout for LGC.

**Comment by trenouf** [comment]
> I feel like all of this would be quite a bit simpler if we just created the LLVM-IR-style descriptor load in the same place as the LLVM-IR-style image sample intrinsic and let CSE do the rest. This is what Mesa does.

That might be a good idea for a future change, but I think that change can be confined to the SPIR-V reader, to slightly simplify how it does the multiple plane thing. So the Builder API is still that you pass in an actual descriptor or array of descriptors.

**Comment by jiaxie-amd** [comment]
Hi Tim,

> With those commits, CreateImageSampleConvert then gets called with an array of 3 image descriptors, and you can use however many of them your "number of planes" bitfield tells you to use. You should be able to rebase your change on top of that, and not need to insert any of your own descriptor loads in the middle of ImageBuilder.
 
Thanks for the commit, I've rebased on your #782, verified that the commit  supports multiPlane image descriptor.

> My commits remain in the old state that the stride of a YCbCrSampler is 12 dwords, and I think you want to change it to 8*planes dwords. The stride is now set in llpc/context/llpcPipelineContext.cpp where the LLPC front-end is setting up the user data layout for LGC.

It works properly after turning the stride from 12 dwords to 8 dwords in llpc/context/llpcPipelineContext.cpp.
