### ISSUE TITLE
Color export shader has wrong PS Input metadata

### ISSUE THREAD

**Issue by s-perron** [GPUOpen-Drivers/llpc#861]
When processing the color export shader[, LLVM will look at the inputs ](https://github.com/GPUOpen-Drivers/llvm-project/blob/amd-gfx-gpuopen-dev/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L1689 )and set metadata values accordingly.  This is just wrong for the color export shaders.

This could be fixed when merging the metadata, but that is not ideal.

This could be fixed in llvm, but would require a way to tell the difference between the actual PS and the color export shader.  **Would creating a new calling convention be a good idea?**

Any suggestions are welcome.

**Comment by s-perron** [comment]
@nhaehnle @trenouf Do either of you have any opinion on how to best fix this?

**Comment by nhaehnle** [comment]
I think Mesa just explicitly ignores the relevant register settings from the color export shader. That doesn't seem too unreasonable to me.

**Comment by trenouf** [comment]
Yeah, I guess that would work, although it's a shame it needs a bit of special case code to ignore or remove the PS inputs metadata on a color export shader.

Maybe an alternative approach would be to use some other shader calling convention. I'm assuming that only PS has this kind of special treatment, and using VS might work. (There is some other special case code in the back-end for other shader CCs to watch out for, e.g. HS and GS assuming they are merged shaders on gfx9+.)

Longer term (i.e. not helping with the immediate problem), I have always wondered why we need to process the PS inputs in the back-end at all. Maybe Mesa needs to, but for PAL we could just handle all that (including the part that says "enable at least one of them because the HW requires that") in LGC.

**Comment by s-perron** [comment]
I don't mind implementing either solution.  If we do what @nhaehnle suggests, then it will require a bit of reworking in the PAL metadata merging because the current code was design to be agnostic about which shaders the values were coming from.  So there is currently no way for the code to know that a value is coming from the glue code or the main shader.

I'm not sure I like the idea of lying to the backend by saying the color export shader is a VS.  This could lead to bugs later when special code is added for vertex shader that we don't want for the color export shader.

**Comment by trenouf** [comment]
I guess we'll have to go with Nicolai's suggestion and making the linker code a bit less general. Maybe a glue shader could have a flag that says "ignore my metadata registers other than vgpr/sgpr/lds usage", and that gets passed that into the linker code. Or something like that.

**Comment by s-perron** [comment]
Okay, I have implemented it by passing a flag that says whether or not the pal metadata being merged in comes from glue code.  The changes are not as intrusive as I thought they would be.
